// ============================================================
// Rotalingo — Curriculum Index
// Combines all 4 levels (180 lessons total) into a single
// exported `curriculum` array and provides lookup utilities.
//
// The individual level files are generated by curriculum-writer
// subagents: data/curriculum/a1.ts, a1-ileri.ts, a2.ts, a2-ileri.ts
// ============================================================

export type {
  TText,
  Level,
  Unit,
  Lesson,
  Exercise,
  MCExercise,
  MCOption,
  DragDropExercise,
  DragDropPair,
  WordOrderExercise,
  FIBExercise,
  RPGExercise,
  RPGNode,
  RPGOption,
  RPGTypingExercise,
  RPGTypingNode,
  TypingMatch,
  LevelCode,
  LessonType,
} from './types';

export {
  shuffle,
  tlocale,
  isLessonUnlocked,
  isUnitUnlocked,
  isLevelUnlocked,
} from './types';

// ── Import level data ────────────────────────────────────────
import { a1Level } from './curriculum/a1';
import { a1IleriLevel } from './curriculum/a1-ileri';
import { a2Level } from './curriculum/a2';
import { a2IleriLevel } from './curriculum/a2-ileri';
import type { Level, Lesson } from './types';

// ── Combined curriculum ──────────────────────────────────────
export const curriculum: Level[] = [a1Level, a1IleriLevel, a2Level, a2IleriLevel];

// ── Flat lesson lookup ───────────────────────────────────────
const allLessons: Lesson[] = curriculum.flatMap((level) =>
  level.units.flatMap((unit) => unit.lessons)
);

export function getLessonById(id: string): Lesson | undefined {
  return allLessons.find((l) => l.id === id);
}

export function getLessonsByUnit(unitId: string): Lesson[] {
  return allLessons.filter((l) => l.id.startsWith(unitId));
}

/** Total lesson count — should be 180 */
export const totalLessons = allLessons.length;
